config/routes.rb
Rails.application.routes.draw do
  flipper_app = Flipper::UI.app(Flipper.instance) do |builder|
    builder.use Rack::Auth::Basic do |username, password|
      username == ENV["FLIPPER_USERNAME"] && password == ENV["FLIPPER_PASSWORD"]
    end
  end
  mount flipper_app, at: "/flipper"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    invitations: "users/invitations"
  }
  resources :children, except: [:destroy] do
    post :active
  end
  resources :families

  resources :authorized_family_members
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  get(
    "/partners/sign_in",
    to: redirect("/users/sign_in")
  )

  get(
    "/partners/invitiation/accept?_inquiry_groups/:id/edit",
    to: redirect(path: "/users/invitation/accept")
  )

  get "dashboard", to: "dashboard#index"

  resources :partners do
    get :approve
  end

  resources :users, only: [:index]
  resources :partner_requests, only: [:new, :create, :show, :index]
  resources :individuals_requests, only: [:new, :create]
  resources :family_requests, only: [:new, :create] do
    resource :pickup_sheets, only: :show
  end

  post "/child_item_requests_toggle_picked_up/:id", action: :toggle_picked_up,
                                                    controller: :child_item_requests,
                                                    as: :child_item_requests_toggle_picked_up
  post "/child_item_requests_quantity_picked_up/:id",
       action: :quantity_picked_up,
       controller: :child_item_requests,
       as: :child_item_requests_quantity_picked_up
  post "/child_item_requests_item_picked_up/:id",
       action: :item_picked_up,
       controller: :child_item_requests,
       as: :child_item_requests_item_picked_up
  post "/child_item_requests_authorized_family_member_picked_up/:id",
       action: :authorized_family_member_picked_up,
       controller: :child_item_requests,
       as: :child_item_requests_authorized_family_member_picked_up

  get "/api", action: :show, controller: "api"
  namespace :api, defaults: { format: "json" } do
    namespace :v1 do
      resources :partners, only: [:create, :show, :update]
      resources :add_partners, only: [:create]
      resources :partner_forms, only: [:create]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "pages/:name", to: "static#page", as: "static_page"
  root "static#index"
end

app/models/family.rb
# == Schema Information
#
# Table name: families
#
#  id                        :bigint(8)        not null, primary key
#  guardian_first_name       :string
#  guardian_last_name        :string
#  guardian_zip_code         :string
#  guardian_country          :string
#  guardian_phone            :string
#  agency_guardian_id        :string
#  home_adult_count          :integer
#  home_child_count          :integer
#  home_young_child_count    :integer
#  sources_of_income         :jsonb
#  guardian_employed         :boolean
#  guardian_employment_type  :jsonb
#  guardian_monthly_pay      :decimal(, )
#  guardian_health_insurance :jsonb
#  comments                  :text
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  partner_id                :bigint(8)
#  military                  :boolean          default(FALSE)
#

class Family < ApplicationRecord
  belongs_to :partner
  has_many :children, dependent: :destroy
  has_many :authorized_family_members, dependent: :destroy
  serialize :sources_of_income, Array
  validates :guardian_first_name, :guardian_last_name, :guardian_zip_code, presence: true

  include Filterable

  filterrific(
    available_filters: [
      :search_guardian_names,
      :search_agency_guardians
    ],
  )

  scope :search_guardian_names, ->(query) { where('guardian_first_name ilike ? OR guardian_last_name ilike ?', "%#{query}%", "%#{query}%") }
  scope :search_agency_guardians, ->(query) { where('agency_guardian_id ilike ?', "%#{query}%") }

  INCOME_TYPES = %w[SSI SNAP/FOOD\ Stamps TANF WIC Housing/subsidized Housing/unsubsidized N/A].freeze
  INSURANCE_TYPES = %w[Private\ insurance Medicaid Uninsured].freeze
  EMPLOYMENT_TYPES = %w[Full-time Part-time N/A].freeze

  after_create :create_authorized

  CSV_HEADERS = %w[
    id guardian_first_name guardian_last_name guardian_zip_code guardian_country
    guardian_phone agency_guardian_id home_adult_count home_child_count home_young_child_count
    sources_of_income guardian_employed guardian_employment_type guardian_monthly_pay
    guardian_health_insurance comments created_at updated_at partner_id military
  ].freeze

  def self.csv_headers
    CSV_HEADERS
  end

  def create_authorized
    authorized_family_members.create!(
      first_name: guardian_first_name,
      last_name: guardian_last_name
    )
  end

  def guardian_display_name
    "#{guardian_first_name} #{guardian_last_name}"
  end

  def total_children_count
    home_child_count + home_young_child_count
  end

  def to_csv
    [
      id,
      guardian_first_name,
      guardian_last_name,
      guardian_zip_code,
      guardian_country,
      guardian_phone,
      agency_guardian_id,
      home_adult_count,
      home_child_count,
      home_young_child_count,
      sources_of_income,
      guardian_employed,
      guardian_employment_type,
      guardian_monthly_pay,
      guardian_health_insurance,
      comments,
      created_at,
      updated_at,
      partner_id,
      military
    ]
  end
end

app/controllers/families_controller.rb
require "csv"
class FamiliesController < ApplicationController
  before_action :authenticate_user!
  helper_method :sort_column, :sort_direction

  def index
    @filterrific = initialize_filterrific(
      current_partner.families
          .order(sort_column + ' ' + sort_direction),
      params[:filterrific]
    ) || return

    @families = @filterrific.find

    respond_to do |format|
      format.js
      format.html
      format.csv do
        render(csv: @families.map(&:to_csv))
      end
    end
  end

  def show
    @family = current_partner.families.find(params[:id])
  end

  def new
    @family = current_partner.families.new
  end

  def edit
    @family = current_partner.families.find(params[:id])
  end

  def create
    @family = current_partner.families.new(family_params)

    if @family.save
      redirect_to @family, notice: "Family was successfully created."
    else
      render :new
    end
  end

  def update
    @family = current_partner.families.find(params[:id])

    if @family.update(family_params)
      redirect_to @family, notice: "Family was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    family = current_partner.families.find_by(id: params[:id])

    if family.present?
      family.destroy
      redirect_to families_url, notice: "Family was successfully destroyed."
    end
  end

  private

  def family_params
    params.require(:family).permit(
      :agency_guardian_id,
      :comments,
      :guardian_country,
      :guardian_employed,
      :guardian_employment_type,
      :guardian_first_name,
      :guardian_health_insurance,
      :guardian_last_name,
      :guardian_monthly_pay,
      :guardian_phone,
      :guardian_zip_code,
      :home_adult_count,
      :home_child_count,
      :home_young_child_count,
      :military,
      sources_of_income: []
    )
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def sort_column
    Family.column_names.include?(params[:sort]) ? params[:sort] : "guardian_last_name"
  end
end

app/views/families/_form.html.erb
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <!-- left column -->
      <div class="col-md-12">
        <!-- jquery validation -->
        <div class="card card-primary">
          <!-- /.card-header -->
          <!-- form start -->
          <div class="card-body">
            <%= simple_form_for family, html: {role: 'form', class: 'form-horizontal'} do |f| %>
              <%= f.input :guardian_first_name, label: "Guardian First Name", class: "form-control", wrapper: :input_group %>

              <%= f.input :guardian_last_name, label: "Guardian Last Name", class: "form-control", wrapper: :input_group %>

              <%= f.input :guardian_zip_code, label: "Guardian Zip Code", class: "form-control", wrapper: :input_group %>

              <%= f.label :guardian_country, "Guardian County" %>
              <%# <i class="fa fa-question-circle" style="color:blue" data-toggle="tooltip" title="Hooray!"></i> %>
              <%= f.text_field :guardian_country, class: "form-control" %>

              <%= f.label :guardian_phone, "Guardian Phone" %>
              <%# <i class="fa fa-question-circle" style="color:blue" data-toggle="tooltip" title="Hooray!"></i> %>
              <%= f.text_field :guardian_phone, class: "form-control" %>

              <%= f.label :agency_guardian_id, "Agency Care Manager" %>
              <i class="fa fa-question-circle" style="color:blue" data-toggle="tooltip" title="Person at the agency who is assigned to this family."></i>
              <%= f.text_field :agency_guardian_id, class: "form-control" %>

              <%= f.label :home_adult_count, "Number of Adults Living In The Home" %>
              <%# <i class="fa fa-question-circle" style="color:blue" data-toggle="tooltip" title="Hooray!"></i> %>
              <%= f.number_field :home_adult_count, class: "form-control" %>

              <%= f.label :home_child_count, 'How Many Children (5-17) Live In The Home?' %>
              <%# <i class="fa fa-question-circle" style="color:blue" data-toggle="tooltip" title="Hooray!"></i> %>
              <%= f.number_field :home_child_count, class: "form-control" %>

              <%= f.label :home_young_child_count, 'How Many Children (under 5) Live In The Home?' %>
              <%# <i class="fa fa-question-circle" style="color:blue" data-toggle="tooltip" title="Hooray!"></i> %>
              <%= f.number_field :home_young_child_count, class: "form-control" %>

              <%= f.label :sources_of_income, "Sources of Income" %>
              <%# <i class="fa fa-question-circle" style="color:blue" data-toggle="tooltip" title="Hooray!"></i> %>
              <br>
              <% Family::INCOME_TYPES.each do |a_value| %>
                   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= f.check_box(:sources_of_income, {:multiple => true}, a_value, nil) %>
                <%= f.label "#{a_value}", "#{a_value}" %>
              <% end %>
              <br>

              <%= f.label :guardian_employed, "Is The Parent/Guardian Employed?" %>
              <%# <i class="fa fa-question-circle" style="color:blue" data-toggle="tooltip" title="Hooray!"></i> %>
              <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= f.radio_button :guardian_employed, 'Yes' %>
              <%= label :guardian_employed, 'Yes' %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <%= f.radio_button :guardian_employed, 'No' %>
              <%= label :guardian_employed, 'No' %>
              <br>

              <%= f.label :guardian_employment_type, "Guardian Employed Full-Time or Part-Time" %>
              <%# <i class="fa fa-question-circle" style="color:blue" data-toggle="tooltip" title="Hooray!"></i> %>
              <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= f.radio_button :guardian_employment_type, 'Full-Time' %>
              <%= label :guardian_employment_type, 'Full-Time' %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <%= f.radio_button :guardian_employment_type, 'Part-Time' %>
              <%= label :guardian_employment_type, 'Part-Time' %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <%= f.radio_button :guardian_employment_type, 'N/A' %>
              <%= label :guardian_employment_type, 'N/A', 'N/A' %>
              <br>

              <%= f.label :guardian_monthly_pay, "Guardian's Monthly Income" %>
              <%# <i class="fa fa-question-circle" style="color:blue" data-toggle="tooltip" title="Hooray!"></i> %>
              <%= f.text_field :guardian_monthly_pay, class: "form-control" %>

              <%= f.label :guardian_health_insurance, "Guardian's Health Insurance Status" %>
              <%# <i class="fa fa-question-circle" style="color:blue" data-toggle="tooltip" title="Hooray!"></i> %>
              <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= f.radio_button :guardian_health_insurance, 'Private Insurance' %>
              <%= label :guardian_health_insurance, 'Private Insurance' %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <%= f.radio_button :guardian_health_insurance, 'Medicaid' %>
              <%= label :guardian_health_insurance, 'Medicaid' %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <%= f.radio_button :guardian_health_insurance, 'Uninsured' %>
              <%= label :guardian_health_insurance, 'Uninsured' %>
              <br>

              <%= f.label :military, "Military Family" %>
              <%# <i class="fa fa-question-circle" style="color:blue" data-toggle="tooltip" title="Hooray!"></i> %>
              <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= f.radio_button :military, true %> <strong>Yes</strong>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= f.radio_button :military, false %> <strong>No</strong>
              <br>
              <%= f.label :comments %>
              <%# <i class="fa fa-question-circle" style="color:blue" data-toggle="tooltip" title="Hooray!"></i> %>
              <%= f.text_area :comments, class: "form-control" %>
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                <%= f.submit(class: 'btn btn-primary') %>
              </div>
            <% end %>
            </div>
        <!-- /.card -->
      </div>

    </div>
    <!-- /.row -->
  </div><!-- /.container-fluid -->
</section>

app/views/families/_list.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th scope="col"><%= sortable "guardian_last_name", "Guardian last name" %></th>
    <th scope="col"><%= sortable "guardian_first_name", "Guardian first name" %></th>
    <th scope="col"><%= sortable "agency_guardian_id", "Agency guardian" %></th>
    <th scope="col">Comments</th>
    <th scope="col" colspan="2">
      <%= link_to 'Export Results To CSV', families_path(nil, format: :csv), class: "btn btn-info pull-right" %>
    </th>
  </tr>
  </thead>
  <tbody>
  <% @families.each do |family| %>
    <tr>
      <td><%= family.guardian_last_name %></td>
      <td><%= family.guardian_first_name %></td>
      <td><%= family.agency_guardian_id %></td>
      <td><%= family.comments %></td>
      <td><%= link_to 'View Family', family, class: "btn btn-sm btn-info pull-right" %></td>
      <td><%= link_to 'Edit Family Details', edit_family_path(family), class: "btn btn-sm btn-success pull-right" %></td>
  <% end %>
  </tbody>
</table>

app/views/families/edit.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <% content_for :title, "Families - #{current_partner.name}" %>
        <h1><i class="fa fa-pencil-square-o"></i>&nbsp;&nbsp;
          Edit Family
          <small>for <%= current_partner.name %></small>
        </h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><%= link_to(dashboard_path) do %>
              <i class="fa fa-home fa-lg"></i> Home
            <% end %>
          </li>
          <li class="breadcrumb-item"><a href="<%= families_path %>">All Families</a></li>
          <li class="breadcrumb-item">
            <a href="<%= family_path(@family) %>">The <%= "#{@family.guardian_last_name}" %> Family</a></li>
          <li class="breadcrumb-item"><a href="#">Edit</a></li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>


<%= render 'form', family: @family %>

app/views/families/index.csv.erb
<%= Family.csv_headers.join(',') %>
<%=
  CSV.generate do |csv|
    @families.each do |family|
      csv << family.to_csv
    end
  end
-%>

app/views/families/index.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <% content_for :title, "Families - #{current_partner.name}" %>
        <h1><i class="fa fa-users"></i>&nbsp;&nbsp;
          Families
          <small>for <%= current_partner.name %></small>
        </h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><%= link_to(dashboard_path) do %>
              <i class="fa fa-dashboard"></i> Home
            <% end %>
          </li>
          <li class="breadcrumb-item"><a href="#">Familes</a></li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <!-- left column -->
      <div class="col-md-12">
        <!-- jquery validation -->
        <div class="card">
          <div class="card-header bg-primary">
            <h3 class="card-title">Filters</h3>
          </div>
          <div class="card-body">
            <%= form_for_filterrific @filterrific, remote: true do |f| %>
              <div class="row">
                <div class="col-3">
                  <%= f.label :search_guardian_names, "Search By Guardian Name" %>
                  <%= f.text_field(
                          :search_guardian_names,
                          class: 'filterrific-periodically-observed form-control'
                      ) %>
                </div>
                <div class="col-3">
                  <%= f.label :search_agency_guardians, "Search By Agency Guardian" %>
                  <%= f.text_field(
                          :search_agency_guardians,
                          class: 'filterrific-periodically-observed form-control'
                      ) %>
                </div>
                <div class="col-3">
                  <%= render_filterrific_spinner %>
                </div>
              </div>
              </div><!-- /.row -->
              <div class="card-footer">
                <%= link_to(
                        'Reset Search',
                        reset_filterrific_url,
                        class: 'btn btn-danger'
                    ) %>
                <span class="float-right">
                  <%= link_to 'Add New Family', new_family_path, class: "btn btn-info" %>
                </span>
            <% end %>
            </div>
        </div>
        <!-- /.card -->
      </div>
      <!--/.col (left) -->
    </div>
    <!-- /.row -->
  </div><!-- /.container-fluid -->
</section>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <!-- Default box -->
        <div class="card">
          <div class="card-body">
            <div id="filterrific_results">
              <%= render(
                      partial: 'families/list',
                      locals: {families: @families}
                  ) %>
            </div>
          </div>
        </div>
        <!-- /.card -->
      </div>
    </div>
  </div>
</section>

app/views/families/index.js.erb
<% js = escape_javascript(
  render(partial: 'families/list', locals: { families: @families })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/families/new.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <% content_for :title, "Families - #{current_partner.name}" %>
        <h1><i class="fa fa-user-plus"></i>&nbsp;&nbsp;
          New Family
          <small>for <%= current_partner.name %></small>
        </h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><%= link_to(dashboard_path) do %>
              <i class="fa fa-home fa-lg"></i> Home
            <% end %>
          </li>
          <li class="breadcrumb-item"><a href="<%= families_path %>">All Families</a></li>
          <li class="breadcrumb-item"><a href="#">New Family</a></li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>


<%= render 'form', family: @family %>

app/views/families/show.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <% content_for :title, "Families - #{current_partner.name}" %>
        <h1><i class="fa fa-users"></i>&nbsp;&nbsp;
          Family Details
          <small>for <%= current_partner.name %></small>
        </h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><%= link_to(dashboard_path) do %>
              <i class="fa fa-home fa-lg"></i> Home
            <% end %>
          </li>
          <li class="breadcrumb-item"><a href="<%= families_path %>">All Families</a></li>
          <li class="breadcrumb-item"><a href="#">The <%= "#{@family.guardian_last_name}" %> Family</a></li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card mb-4">
          <h5 class="card-header bg-primary text-white">Family Information
            <%= link_to 'Add An Authorized Member To This Family', new_authorized_family_member_path(family_id: @family.id), class: "btn btn-sm btn-warning pull-right", style: "margin-left:10px;" %>
            <%= link_to 'Add Child To This Family', new_child_path(family_id: @family.id), class: "btn btn-sm btn-warning pull-right" %>
          </h5>
          <div class="card-body">
            <dl>
              <dt>Guardian First Name:</dt>
              <dd><%= @family.guardian_first_name %></dd>

              <dt>Guardian Last Name:</dt>
              <dd><%= @family.guardian_last_name %></dd>

              <dt>Guardian Zip Code:</dt>
              <dd><%= @family.guardian_zip_code %></dd>

              <dt>Guardian County:</dt>
              <dd><%= @family.guardian_country %></dd>

              <dt>Guardian Phone:</dt>
              <dd><%= @family.guardian_phone %></dd>

              <dt>Agency Care Manager:</dt>
              <dd><%= @family.agency_guardian_id %></dd>

              <dt>Home Adult Count:</dt>
              <dd><%= @family.home_adult_count %></dd>

              <dt>Number of Children Aged 5-17 in the Home:</dt>
              <dd><%= @family.home_child_count %></dd>

              <dt>Number of Children Under Age 5 in the Home:</dt>
              <dd><%= @family.home_young_child_count %></dd>

              <dt>Sources of Income:</dt>
              <dd><%= @family.sources_of_income.join(', ') %></dd>

              <dt>Guardian Employed:</dt>
              <dd><%= @family.guardian_employed ? "Yes" : "No" %></dd>

              <dt>Guardian Employment Type:</dt>
              <dd><%= @family.guardian_employment_type %></dd>

              <dt>Guardian Monthly Pay:</dt>
              <dd><%= @family.guardian_monthly_pay %></dd>

              <dt>Guardian Health Insurance:</dt>
              <dd><%= @family.guardian_health_insurance %></dd>

              <dt>Military Family:</dt>
              <dd><%= @family.military ? "Yes" : "No" %></dd>

              <dt>Comments:</dt>
              <dd><%= @family.comments %></dd>
            </dl>
          </div>
          <div class="card-footer">
            <%= link_to 'Edit This Family', edit_family_path(@family), class: "btn btn-sm btn-primary" %>
            <%= link_to 'Back to Families', families_path, class: "btn btn-sm btn-info pull-right" %>
            <%= link_to 'Add Child To This Family', new_child_path(family_id: @family.id), class: "btn btn-sm btn-success" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card mb-4">
          <h5 class="card-header bg-primary text-white">Children Information</h5>
          <table class="table table-striped">
            <thead>
            <tr>
              <th style="width: 13.33%">First Name</th>
              <th style="width: 13.33%">Last Name</th>
              <th style="width: 13.33%">Date of Birth</th>
              <th style="width: 45%">Gender</th>
              <th style="width: 15%">Actions</th>
            </tr>
            </thead>
            <tbody>
            <% @family.children.each do |child| %>
              <tr>
                <td><%= child.first_name %></td>
                <td><%= child.last_name %></td>
                <td><%= child.date_of_birth %></td>
                <td><%= child.gender %></td>
                <td><%= link_to 'Edit', edit_child_path(child), class: "btn btn-sm btn-outline-primary" %></td>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card mb-4">
          <h5 class="card-header bg-primary text-white">Authorized Members for Pick Up</h5>
          <table class="table table-striped">
            <thead>
            <tr>
              <th style="width: 13.33%">First Name</th>
              <th style="width: 13.33%">Last Name</th>
              <th style="width: 13.33%">Date of Birth</th>
              <th style="width: 45%">Comments</th>
              <th style="width: 15%">Actions</th>
            </tr>
            </thead>
            <tbody>
            <% @family.authorized_family_members.each do |member| %>
              <tr>
                <td><%= member.first_name %></td>
                <td><%= member.last_name %></td>
                <td><%= member.date_of_birth %></td>
                <td><%= member.comments %></td>
                <td>
                  <%= link_to 'Edit', edit_authorized_family_member_path(member), class: "btn btn-sm btn-outline-primary" %>
                  <%= link_to 'View', authorized_family_member_path(member), class: "btn btn-sm btn-outline-info" %>
                  <%= link_to 'Delete', authorized_family_member_path(member), class: "btn btn-sm btn-outline-danger",
                       data: { confirm: "Are you sure?" }, method: :delete%>
                </td>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>