config/routes.rb
Rails.application.routes.draw do
  flipper_app = Flipper::UI.app(Flipper.instance) do |builder|
    builder.use Rack::Auth::Basic do |username, password|
      username == ENV["FLIPPER_USERNAME"] && password == ENV["FLIPPER_PASSWORD"]
    end
  end
  mount flipper_app, at: "/flipper"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    invitations: "users/invitations"
  }
  resources :children, except: [:destroy] do
    post :active
  end
  resources :families

  resources :authorized_family_members
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  get(
    "/partners/sign_in",
    to: redirect("/users/sign_in")
  )

  get(
    "/partners/invitiation/accept?_inquiry_groups/:id/edit",
    to: redirect(path: "/users/invitation/accept")
  )

  get "dashboard", to: "dashboard#index"

  resources :partners do
    get :approve
  end

  resources :users, only: [:index]
  resources :partner_requests, only: [:new, :create, :show, :index]
  resources :individuals_requests, only: [:new, :create]
  resources :family_requests, only: [:new, :create] do
    resource :pickup_sheets, only: :show
  end

  post "/child_item_requests_toggle_picked_up/:id", action: :toggle_picked_up,
                                                    controller: :child_item_requests,
                                                    as: :child_item_requests_toggle_picked_up
  post "/child_item_requests_quantity_picked_up/:id",
       action: :quantity_picked_up,
       controller: :child_item_requests,
       as: :child_item_requests_quantity_picked_up
  post "/child_item_requests_item_picked_up/:id",
       action: :item_picked_up,
       controller: :child_item_requests,
       as: :child_item_requests_item_picked_up
  post "/child_item_requests_authorized_family_member_picked_up/:id",
       action: :authorized_family_member_picked_up,
       controller: :child_item_requests,
       as: :child_item_requests_authorized_family_member_picked_up

  get "/api", action: :show, controller: "api"
  namespace :api, defaults: { format: "json" } do
    namespace :v1 do
      resources :partners, only: [:create, :show, :update]
      resources :add_partners, only: [:create]
      resources :partner_forms, only: [:create]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "pages/:name", to: "static#page", as: "static_page"
  root "static#index"
end

app/controllers/individuals_requests_controller.rb
class IndividualsRequestsController < ApplicationController
  helper MultiItemFormHelper

  before_action :authenticate_user!
  before_action :verify_status_in_diaper_base
  before_action :authorize_verified_partners

  def new
    @request = FamilyRequest.new({}, initial_items: 1)
  end

  def create
    @request = FamilyRequest.new(family_request_params, partner: current_partner)

    FamilyRequestService.execute(@request)

    redirect_to partner_requests_path, notice: "Requested items successfuly!"
  rescue ActiveModel::ValidationError
    render :new
  end

  private

  def family_request_params
    params.require(:family_request)
          .permit(:comments, items_attributes: %i[item_id person_count])
  end
end

app/views/individuals_requests/_item_request.html.erb
<%= form.fields_for(:items) do |field| %>
  <tr>
    <td><%= field.input :item_id, collection: valid_items_for_select(valid_items), label: false, allow_blank: true, class: 'form-control' %></td>
    <td><%= field.input :person_count, as: :integer, label: false, step: 1, min: 1, class: 'form-control' %></td>
    <td><%= remove_item_button "Remove" %></td>
  </tr>
<% end %>

app/views/individuals_requests/new.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <% content_for :title, "New Individuals Request - #{current_partner.name}" %>
        <h1><i class="fa fa-users"></i>&nbsp;&nbsp;
          New Request
          <small>for <%= current_partner.name %></small>
        </h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="<%= dashboard_path %>"><i class="fa fa-home fa-lg"></i></a></li>
          <li class="breadcrumb-item"><a href="#">New Invididuals Order Request</a></li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <!-- Default box -->
        <div class="card">
          <div class="card-body">

            <%= simple_form_for @request, url: individuals_requests_path, html: {role: 'form', class: 'form-horizontal'} do |form| %>
              <%= form.input :comments, label: "Comments:", as: :text, class: "form-control", wrapper: :input_group %>

              <table class='table'>
                <thead>
                <tr>
                  <th>Item Requested</th>
                  <th>Number of Individuals</th>
                  <th></th>
                </tr>
                </thead>
                <tbody class='fields'>
                  <%= render 'individuals_requests/item_request', form: form %>
                </tbody>
              </table>

              <div>
                <%= add_item_button('Add Another Item') do %>
                  <%= render 'individuals_requests/item_request', form: form %>
                <% end %>
              </div>

              <hr />

              <div class="card-footer">
                <!-- TODO(chaserx): we should add some js to prevent submission if the items selected are the blank option or any item has an empty quantity -->
                <%= form.submit("Submit Essentials Request", class: "btn btn-primary") %>
                <%= link_to "Cancel Request", partner_requests_path, class: "btn btn-danger" %>
              </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</section>