config/routes.rb
Rails.application.routes.draw do
  flipper_app = Flipper::UI.app(Flipper.instance) do |builder|
    builder.use Rack::Auth::Basic do |username, password|
      username == ENV["FLIPPER_USERNAME"] && password == ENV["FLIPPER_PASSWORD"]
    end
  end
  mount flipper_app, at: "/flipper"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    invitations: "users/invitations"
  }
  resources :children, except: [:destroy] do
    post :active
  end
  resources :families

  resources :authorized_family_members
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  get(
    "/partners/sign_in",
    to: redirect("/users/sign_in")
  )

  get(
    "/partners/invitiation/accept?_inquiry_groups/:id/edit",
    to: redirect(path: "/users/invitation/accept")
  )

  get "dashboard", to: "dashboard#index"

  resources :partners do
    get :approve
  end

  resources :users, only: [:index]
  resources :partner_requests, only: [:new, :create, :show, :index]
  resources :individuals_requests, only: [:new, :create]
  resources :family_requests, only: [:new, :create] do
    resource :pickup_sheets, only: :show
  end

  post "/child_item_requests_toggle_picked_up/:id", action: :toggle_picked_up,
                                                    controller: :child_item_requests,
                                                    as: :child_item_requests_toggle_picked_up
  post "/child_item_requests_quantity_picked_up/:id",
       action: :quantity_picked_up,
       controller: :child_item_requests,
       as: :child_item_requests_quantity_picked_up
  post "/child_item_requests_item_picked_up/:id",
       action: :item_picked_up,
       controller: :child_item_requests,
       as: :child_item_requests_item_picked_up
  post "/child_item_requests_authorized_family_member_picked_up/:id",
       action: :authorized_family_member_picked_up,
       controller: :child_item_requests,
       as: :child_item_requests_authorized_family_member_picked_up

  get "/api", action: :show, controller: "api"
  namespace :api, defaults: { format: "json" } do
    namespace :v1 do
      resources :partners, only: [:create, :show, :update]
      resources :add_partners, only: [:create]
      resources :partner_forms, only: [:create]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "pages/:name", to: "static#page", as: "static_page"
  root "static#index"
end

app/models/partner_request.rb
# == Schema Information
#
# Table name: partner_requests
#
#  id              :bigint(8)        not null, primary key
#  comments        :text
#  partner_id      :bigint(8)
#  organization_id :bigint(8)
#  sent            :boolean          default(FALSE), not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  for_families    :boolean
#

class PartnerRequest < ApplicationRecord
  belongs_to :partner

  has_many :item_requests, dependent: :destroy
  accepts_nested_attributes_for :item_requests, allow_destroy: true,
                                                reject_if: proc { |attributes| attributes["quantity"].blank? }
  validates :item_requests, presence: true, if: proc { |a| a.comments.blank? }
  has_many :child_item_requests, through: :item_requests

  validates :partner, presence: true
  validates_associated :item_requests

  def export_json
    {
      request: {
        partner_id: partner.diaper_partner_id,
        organization_id: partner.diaper_bank_id,
        comments: comments,
        request_items: formatted_item_requests_hash(item_requests)
      }
    }.to_json
  end

  def formatted_item_requests_hash(item_requests)
    item_requests.map { |item| { "item_id" => item.item_id, "quantity" => item.quantity } }
  end
end

app/controllers/partner_requests_controller.rb
class PartnerRequestsController < ApplicationController
  helper MultiItemFormHelper

  before_action :authenticate_user!
  before_action :verify_status_in_diaper_base, only: %i[new create]
  before_action :authorize_verified_partners, only: %i[new]

  def index
    @partner = current_partner
    @partner_requests = current_partner.partner_requests.order(created_at: :desc) # PartnerRequest.where(partner_id: current_partner.id)
  end

  def new
    @partner_request = PartnerRequest.new
    @partner_request.item_requests.build # required to render the empty items form
  end

  def create
    @partner_request = PartnerRequest.new(partner_request_params.merge(partner_id: current_partner.id))
    @partner_request.item_requests << create_item_requests
    respond_to do |format|
      if @partner_request.save
        # NOTE(chaserx): send request to diaper app.
        if DiaperBankClient.request_submission_post(@partner_request.id)
          @partner_request.update(sent: true)
        else
          @partner_request.errors.add(:base, :sending_failure, message: "Your request saved but failed to send")
        end
        format.html { redirect_to partner_requests_path, notice: "Request was successfully created." }
      else
        format.html { render :new }
      end
    end
  end

  def show
    @partner_request = PartnerRequest.find(params[:id])
    authorize @partner_request
  end

  private

  def partner_request_params
    params.require(:partner_request).permit(:comments, :item_requests_attributes)
  end

  def get_full_item_values(id)
    valid_items = DiaperBankClient.get_available_items(current_partner.diaper_bank_id)
    valid_items.find { |item| item["id"] == id.to_i }
  end

  def create_item_requests
    item_params = params.dig("partner_request", "item_requests_attributes")&.values
    item_params.reject! { |item| item["item_id"].empty? }
    item_params.map do |item|
      full_item = get_full_item_values(item["item_id"])
      ItemRequest.new(
        item_id: item["item_id"],
        quantity: item["quantity"],
        name: full_item["name"],
        partner_key: full_item["partner_key"]
      )
    end
  end
end

app/views/partner_requests/_item_request.html.erb
<%= form.fields_for :item_requests, defined?(object) ? object : nil  do |field| %>
  <tr>
    <td><%= field.select :item_id, valid_items_for_select(valid_items), {include_blank: 'Select an item'}, {class: 'form-control'} %></td>
    <td><%= field.number_field :quantity, label: false, step: 1, min: 1, class: 'form-control' %></td>
    <td>
      <%= field.hidden_field :_destroy, as: :hidden %>
      <%= remove_item_button "Remove", soft: true %>
    </td>
  </tr>
<% end %>

app/views/partner_requests/_request_card.html.erb
<div class="card mb-4">
  <h5 class="card-header bg-info">Request Essentials</h5>
  <div class="card-body">
    <div class="container-fluid">
      <div class="row text-center">
        <div class="col-4">
          <h2><%= link_to new_partner_request_path, class: 'btn btn-primary' do %>
              <i class="fa fa-shopping-basket"></i> Create New Bulk Essentials Request
              <% end %>
              </h2>
          <h6>Use this type of request when you want to specify the number of diapers, period supplies, and
            other essentials. Example - 1000 Size 1 Diapers, 500 Tampons, etc.</h6>
        </div>
        <div class="col-4">
          <h2><%= link_to new_family_request_path, class: 'btn btn-primary' do %>
              <i class="fa fa-users"></i> Create New Family Essentials Request
            <% end %>
          </h2>
          <h6>Use this type of request when you you are using the children and family functionality and are
            identifying the specific children you are requesting for.</h6>
        </div>
        <div class="col-4">
          <h2><%= link_to new_individuals_request_path, class: 'btn btn-primary' do %>
              <i class="fa fa-user"></i> Create New Individuals Essentials Request
            <% end %>
          </h2>
          <h6>Use this type of request when you want to just request by the number of individuals in a
            specific category. Example - 10 individuals for Size 1 diapers, 5 individuals need tampons,
            etc.</h6>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partner_requests/index.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <% content_for :title, "Essentials Requests - #{current_partner.name}" %>
        <h1><i class="fa fa-edit"></i>&nbsp;&nbsp;Essentials Requests
          <small>for <%= current_partner.name %></small>
        </h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><%= link_to(dashboard_path) do %>
              <i class="fa fa-dashboard"></i> Home
            <% end %>
          </li>
          <li class="breadcrumb-item">
            <a href="<%= partner_path(current_partner) %>"><%= "#{current_partner.name}" %></a></li>
          <li class="breadcrumb-item"><a href="#">Essentials Requests</a></li>
        </ol>
      </div>
    </div>`
  </div><!-- /.container-fluid -->
</section>


<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <!-- Default box -->
        <%= render 'request_card' if @partner.verified? %>
        <div class="card">
          <div class="card-header bg-info">
            <h1 class="card-title">Request History</h1>
          </div>
          <div class="card-body p-0">

            <table class="table">
              <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Contents</th>
                <th scope="col">Pickup Sheet</th>
                <th scope="col">Request Date</th>
              </tr>
              </thead>
              <tbody>
              <% @partner_requests.each do |partner_request| %>
                <tr>
                  <th scope="row"><%= link_to partner_request.id, partner_request_path(partner_request) %></th>
                  <td><%= partner_request.item_requests.map { |item| "#{item.quantity} of #{item.name}" }.join(", ") %></td>
                  <td>
                    <% if partner_request.for_families? %>
                      <%= link_to family_request_pickup_sheets_path(partner_request),
                                  class: 'btn btn-sm btn-info' do %>
                        <i class="fa fa-edit"></i> Pickup Sheet
                      <% end %>
                    <% end %>
                  </td>
                  <td><%= partner_request.created_at.strftime("%B %-d %Y") %></td>
                </tr>
                </tbody>
              <% end %>
              </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/partner_requests/new.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <% content_for :title, "New Request - #{current_partner.name}" %>
        <h1><i class="fa fa-users"></i>&nbsp;&nbsp;
          New Request
          <small>for <%= current_partner.name %></small>
        </h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">

          <li class="breadcrumb-item"><a href="<%= dashboard_path %>"><i class="fa fa-home fa-lg"></i></a></li>
          <li class="breadcrumb-item"><a href="#">New Essentials Request</a></li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <!-- Default box -->
        <div class="card">
          <div class="card-body">

            <%= simple_form_for @partner_request, html: {role: 'form', class: 'form-horizontal'} do |form| %>

              <%= form.input :comments, label: "Comments:", as: :text, class: "form-control", wrapper: :input_group %>

              <table class='table'>
                <thead>
                <tr>
                  <th>Item Requested</th>
                  <th>Quantity</th>
                  <th></th>
                </tr>
                </thead>
                <tbody class='fields'>
                  <%= render 'item_request', form: form %>
                </tbody>
              </table>
              <div>
                <%= add_item_button('Add Another Item') do %>
                  <%= render 'item_request', form: form, object: @partner_request.item_requests.build %>
                <% end %>
              </div>

              <hr>

          </div>
              <div class="card-footer">
                <!-- TODO(chaserx): we should add some js to prevent submission if the items selected are the blank option or any item has an empty quantity -->
                <%= form.submit("Submit Essentials Request", class: "btn btn-primary") %> <%= link_to "Cancel Request", partner_requests_path, class: "btn btn-danger" %>
              </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/partner_requests/show.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <% content_for :title, "Bulk Request - #{current_partner.name}" %>
        <h1><i class="fa fa-doc"></i>&nbsp;&nbsp;
          Request
          <small>for <%= current_partner.name %></small>
        </h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="<%= dashboard_path %>"><i class="fa fa-home fa-lg"></i></a></li>
          <li class="breadcrumb-item"><a href="#">Request</a></li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>


<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header bg-primary">
            <h3 class="card-title">Request Details</h3>
          </div>
          <div class="card-body">
            <div>
              <h2><%= @partner_request.partner.name %> Request ID: <%= @partner_request.id %></h2>
            </div>

            <div>
              Comments:
              <p><%= @partner_request.comments %></p>
            </div>

            <div>
              Requested Items:
              <ul>
                <% @partner_request.item_requests.each do |item| %>
                  <li><%= item.quantity %> of <%= item.name %></li>
                <% end %>
              </ul>
            </div>
            <div>
              <p>Submitted: <%= @partner_request.created_at.localtime.strftime('%F %T') %></p>
            </div>
            <p><%= link_to "Your Previous Requests", partner_requests_path, class: 'btn btn-success' %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>